### ISSUE TITLE
Ошибка при выполнение запросов через Swagger

### ISSUE THREAD

**Issue by vitalmizevich** [epam-dotnet-lab/northwind-data-services-task#3]
После конфигурирования Swagger и попытке выполнить через UI запрос, мы получаем ошибку “ TypeError: Failed to fetch”. (более подробно здесь: https://stackoverflow.com/questions/45156665/swagger-ui-typeerror-failed-to-fetch-on-valid-response)

Для её решения нам нужно включить CORS (о чем в задании не сказано).
https://docs.microsoft.com/ru-ru/aspnet/core/security/cors?view=aspnetcore-3.1
https://stackoverflow.com/questions/44379560/how-to-enable-cors-in-asp-net-core-webapi

Ниже прикреплен результат запроса в консоли браузера:
![error](https://user-images.githubusercontent.com/20145590/70649296-e05dc780-1c5d-11ea-877a-02c409b5228b.png)

**Comment by alexander-rykov** [comment]
1) Взял апп из папки https://github.com/epam-dotnet-lab/northwind-data-services-task/tree/master/task02/northwind-basic-app-final-3/NorthwindWebApiApp
2) Собрал, запустил, вызвал /api/v1.0/orders
3) Все норм

![image](https://user-images.githubusercontent.com/19323417/70656274-d42c3700-1c6a-11ea-925c-7c2aac8fcfcc.png)

**Comment by vitalmizevich** [comment]
Видимо проблема была в версии Swashbuckle.AspNetCore, изначально установлена 5.0.0-rc3.
